# Generated by Django 5.0.7 on 2024-08-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individualitys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuality',
            name='description',
        ),
    ]
