# Generated by Django 5.0.7 on 2024-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individualitys', '0002_remove_individuality_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuality',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
