# Generated by Django 5.0.7 on 2024-08-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='match_videos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.category')),
            ],
        ),
    ]
