# Generated by Django 5.0.7 on 2024-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='video',
            field=models.FileField(upload_to='media/match_videos/'),
        ),
    ]
