# Generated by Django 5.0.7 on 2024-08-11 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrys', '0001_initial'),
        ('matches', '0002_alter_match_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countrys.country'),
        ),
    ]
