# Generated by Django 5.0.7 on 2024-08-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_finale_result'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='first_team_matches', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='second',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='second_team_matches', to='teams.team'),
            preserve_default=False,
        ),
    ]
