# Generated by Django 5.0.7 on 2024-08-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
