# Generated by Django 5.0.7 on 2024-08-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countrys', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='countrys.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.CharField(blank=True, choices=[('Gardien de But', 'Gardien de But'), ('Arrière Droit', 'Arrière Droit'), ('Arrière Gauche', 'Arrière Gauche'), ('Défenseur Central', 'Défenseur Central'), ('Libéro', 'Libéro'), ('Arrière Latéral Droit', 'Arrière Latéral Droit'), ('Arrière Latéral Gauche', 'Arrière Latéral Gauche'), ('Milieu Central', 'Milieu Central'), ('Milieu Défensif', 'Milieu Défensif'), ('Milieu Offensif', 'Milieu Offensif'), ('Milieu Droit', 'Milieu Droit'), ('Milieu Gauche', 'Milieu Gauche'), ('Attaquant', 'Attaquant'), ('Deuxième Attaquant', 'Deuxième Attaquant')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strong_feet',
            field=models.CharField(blank=True, choices=[('Droit', 'Droit'), ('Gauche', 'Gauche')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weak_feet',
            field=models.CharField(blank=True, choices=[('Droit', 'Droit'), ('Gauche', 'Gauche')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
