# Generated by Django 5.0.7 on 2024-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_position_player_club_and_more'),
        ('postes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='positions',
        ),
        migrations.AlterField(
            model_name='player',
            name='strong_feet',
            field=models.CharField(choices=[('Droit', 'Droit'), ('Gauche', 'Gauche')], max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(to='postes.position'),
        ),
    ]
